---
os: linux
dist: bionic

addons:
  apt:
    packages:
      - make

install:
  - make install

# always make sure hugo can compile the website
script:
  - hugo

deploy:
  - provider: script
    script:
      - make deploy
    skip_cleanup: true
    on:
      branch: master
