baseURL = "https://sugarraysam.github.io"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "SugarRaySam"
    author = "sugarraysam"
    description = "Resume of sugarraysam"

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "dark"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = true

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Samuel Blais-Dowdy"
        tagline = "\U0001f314 I will code you the moon \U0001f312"
        location = "Madison, Wisconsin, USA"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "#"
            title = "LinkedIn"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "#"
            title = "GitHub"

    # Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "DevOps Engineer with Linux, Kubernetes, Docker and Go experience. I am currently investing a lot of my personal time to master gRPC, protobufs and microservices patterns."

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "DevOps Engineer"
            dates = "2020 - *Present*"
            company = "Epic"
            details = """
- Maintain, deploy and monitor k8s clusters
- Help developers with their serverless or RESTful microservices projects in Go
- Maintain infrastructure required to develop and deploy applications on k8s (artifactory, gitlab CI/CD)
- Lead project to export logs and metrics from k8s to Splunk
            """
        [[params.experience.list]]
            position = "DevOps Engineer"
            dates = "2019 - 2020"
            company = "Bell Canada"
            details = """
- Delivered a pipeline for a monolithic Django web application using Gitlab CI, Ansible roles and systemd services
- Delivered a pipeline and helped to migrate the Django monolith to a microservices architecture, using Go, Gitlab CI, docker swarm and Ansible roles
- Performed production shutdown maintenance
- Configured alpine containers for production
            """
        [[params.experience.list]]
            position = "Security Analyst"
            dates = "2018 - 2019"
            company = "Bell Canada"
            details = """
- Performed analysis and escalation of security threats in collaboration with Senior Security Analysts
- Participated in high-impact cybersecurity incident response and wrote report for management
- Helped improve our “Use Cases” by providing feedback to Threat Hunters
- Used Arcsight SIEM along with other hacker tools during investigations (Nmap, traceroute, OpenSSL, Wireshark, F5 WAF, vendor dashboards, Radware, Arbor, etc)
            """
        [[params.experience.list]]
            position = "Teaching Assistant"
            dates = "2018"
            company = "University of Montreal"
            details = """
- Prepared weekly cybersecurity labs for graduate and undergraduate students
- Gave two lectures on symmetric/assymetric cryptography
- Demonstrated and explained popular security tools
- Created and corrected two homeworks for the students, the second being a full exploit of a Vulnhub VM:
    * Fingerprinting
    * RCE/reverse shell obtained from vulnerable PHP web app
    * Linux privilege escalation
- Formulated and corrected some exam questions
            """

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "B.A. in Computer Science and Mathematics"
            college = "University of Montreal"
            dates = "2015 - 2018"
        [[params.education.list]]
            degree = "B.A. in Accounting"
            college = "University of Quebec in Abitibi-Temiscamingue"
            dates = "2012 - 2015"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Archsugar"
            url = "https://github.com/sugarraysam/archsugar"
            description = "Bootstrap, provision and fully maintain an high-end modular archlinux system with Go & Ansible"
        [[params.project.list]]
            title = "Resume"
            url = "https://github.com/sugarraysam/resume"
            description = "Generate and publish my resume with Hugo & Github Pages"

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Go, Linux, Docker, Bash, Alpine"
            skillrating = 90
        [[params.skill.list]]
            skill = "Python, Ansible, Makefile, Git"
            skillrating = 80
        [[params.skill.list]]
            skill = "Gitlab CI/CD, gRPC, Travis CI/CD"
            skillrating = 70
        [[params.skill.list]]
            skill = "Kubernetes, Rust, GraphQL"
            skillrating = 50
        [[params.skill.list]]
            skill = "Robotics"
            skillrating = 20

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]
            hobby = "\U0001f4bb Programming"
        [[params.hobby.list]]
            hobby = "\U0001f3d2 Ice Hockey"
        [[params.hobby.list]]
            hobby = "\U0001f916 Robotics"
        [[params.hobby.list]]
            hobby = "\U0001f3be Tennis"
        [[params.hobby.list]]
            hobby = "\U0001f37a Microbrewery Hunting"
        [[params.hobby.list]]
            hobby = "\U0001f3cb Working Out"
